services:
  - type: web
    name: docqa
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PGVECTOR_HOST
        sync: false
      - key: PGVECTOR_PORT
        sync: false
      - key: PGVECTOR_DB
        sync: false
      - key: PGVECTOR_USER
        sync: false
      - key: PGVECTOR_PASSWORD
        sync: false